---
name: KeepInventory
version: 3.1.1
main: NhanAZ\KeepInventory\Main
api: 5.0.0
website: https://github.com/NhanAZ
author: NhanAZ
authors: [KhoaGamingVN]
description: Prevents players from losing items on death
...
