---
name: KeepInventory
version: 2.1.1
main: KeepInventory\KeepInventory
src-namespace-prefix: KeepInventory
api: 4.0.0
website: https://github.com/NhanAZ
author: NhanAZ
authors: [KhoaGamingVN]
description: Prevents players from losing items on death
...
