---
# KeepInventory Mode
# true : Prevents players from losing items on death
# false : Players from losing items on death
KeepInventory: true

# all : All worlds will be affected by KeepInventory Mode
# whitelist : All worlds listed below will be affected by KeepInventory Mode
# blacklist : All worlds not listed below will be affected by KeepInventory Mode
Mode: all
Worlds: []
# Worlds: ["world1", "world2"]
...
