---
# Value: true or false
# Default value: true (Recomend using)
#
# Value description:
# : true (Items in the player's inventory will be kept after the they die)
# : false (Items in the player's inventory will be lost after the they die)
KeepInventory: true

# Value: "MessageAfterDeath (String)"
# Default value: §aItems in your inventory have been kept
#
# Value description: Notifications sent to players after they die
MessageAfterDeath: "Items in your inventory have been kept"

# Value: none, message, popup, tip, title, subtitle, actionbarmessage
# Default value: none (Recomend using)
#
# Value description:
# : none (No messages have been sent to the player)
# : message (Sends a direct chat message to a player)
# : title (Send a title text to the user's screen)
# : popup (Sends a popup message to the player)
# : tip (Sends a tip message to the player)
# : actionbarmessage (Send a small text to the user's screen)
MessageType: none
...
