# Config file

# Keep inventory true or false
KeepInventory: true

# Message types: message, popup, tip, title
MessageType: message

# Message after player's inventory has been kept
MessageAfterDeath: "§aYour inventory has been kept"
