---
# true : Prevents players from losing items on death
# false : Use the server's default keep inventory mode (keepInventory=false)
keepInventory: true

# all : All worlds will be affected by KeepInventory Mode
# whitelist : All worlds listed below will be affected by KeepInventory Mode
# blacklist : All worlds not listed below will be affected by KeepInventory Mode
mode: all
worlds: []
# worlds: ["world1", "world2"]
...
